### ISSUE TITLE
Why does this model needs at least 716 days to run?

### ISSUE THREAD

**Issue by dimrizo** [Quantiacs/quantiacs-python#5]
since the lookback is 504 days shouldn't it need only 504 days to run once?

**Comment by YalaTest** [comment]
Hi @dimrizo ,

Just want to make sure we are clear on the definition of _lookback_:
[[http://quantiacs-python-toolbox-documentation.readthedocs.io/en/latest/ts_structure.html?highlight=lookback]](url)
> Where lookback is simply how many historical data points you want to load in each iteration of your trading system. Given the data is daily, lookback represents the maximum number of days of market data you want to have loaded.

Each day in the lookback period is a historical data point, which is a trading day. Excluding holidays and weekends, there are approximately 250 trading days a year. A lookback of 504 is about 2 years length, and there are over 700 calendar days in 2 years. This could be the reason that your program needs at least 716 days to run with a lookback of 504.

Please let me know if this does not answer the issue.
Thanks.
